// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"knowFood/internal/handler/v1"
	"knowFood/internal/handler/v1/user"
	"knowFood/internal/repo/mysql"
	"knowFood/internal/router"
	"knowFood/internal/service"
	"knowFood/server"
	"knowFood/utils/db"
)

// Injectors from wire.go:

// initRouter initializes and returns the router for the server
func initRouter(ds db.IDataSource) server.Router {
	userRepo := mysql.NewUserRepo(ds)
	userService := service.NewUserService(userRepo)
	handler := user.NewUserHandler(userService)
	apiRouter := router.NewApiRouter(handler)
	return apiRouter
}

// wire.go:

var providerSet = wire.NewSet(mysql.ProviderSet, service.ProviderSet, v1.ProviderSet)
